### ISSUE TITLE
nginx.conf file

### ISSUE THREAD

**Issue by kwstasna** [ltebean/Live#1]
Could you please share your nginx.conf file? Because we are the noobies here and don't know anything about Nginx :( 
Just to mention that your app with your server runs perfect and i'm trying to make it on my own!

**Comment by ltebean** [comment]
Just add this block into nginx.conf
```
rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                }
        }
}
```

Then you can push the stream to rtmp://your-server-ip/live/{streamKey}

**Comment by kwstasna** [comment]
Peftect it works like a charm. Thanks a lot!

**Comment by kwstasna** [comment]
FYI. Because i have no knowledge about nginx and server side stuff i made a droplet at digitalocean and followed this guide.

https://www.atlantic.net/community/howto/install-rtmp-ubuntu-14-04/

Pasted your code at the file nginx.conf as the above tutorial says and it works.
Nice!!!

**Comment by ltebean** [comment]
cool, I will add put guide into readme, thanks!

**Comment by wazowski78** [comment]
the tutorial is suppose to be followed from start to end? I mean, I don't know if I have to set up this part too: 

"Additional Configurations

At this point, your server is all set up and configured with RMTP. However, to begin  streaming,  you can  download “Open Broadcaster Software “software free of charge and configure the broadcast settings to the following... "

**Comment by ltebean** [comment]
after set up the nginx rtmp server, you can use the app to to begin streaming, just modify the Config.swift to make the server url point to your nginx rtmp server

**Comment by ricking06** [comment]
i folloed the guide at 
https://www.atlantic.net/community/howto/install-rtmp-ubuntu-14-04/ 

(I havent yet installed ewbsocket/ios/ or anything.)

I went to obs 

and used 

URL : `rtmp://127.0.0.1/live`
Stream Key:  `mystreamkey`

But it says could not connect ?

i also tried `rtmp://127.0.0.1:8081/live`, `rtmp://127.0.0.:81/live`

I have changed my nginx port in 81 instead of 80.
