### ISSUE TITLE
second launch crashed.

### ISSUE THREAD

**Issue by DreamXiao** [ltebean/Live#12]
i have changed 
![123](https://cloud.githubusercontent.com/assets/4948854/18664231/3f1ab92c-7f54-11e6-9fe1-283b344db893.png)
in Config.swift
and i run node app.js success and terminal display listening on port 3000...
for the first time it works well.but second time it crashed like below:
<img width="1397" alt="123" src="https://cloud.githubusercontent.com/assets/4948854/18664107/e57df37a-7f53-11e6-80a3-f9e80d9bc39c.png">

**Comment by DreamXiao** [comment]
By the way,for iOS 9 (iPhone6 plus) and iOS 10(iPhone6) are the same issue.

**Comment by ltebean** [comment]
Did you set up your own rtmp server?

**Comment by ltebean** [comment]
This project is just for demonstration. The 'VideoCore' component do have some bugs. In production, you are likely to use the official streaming sdk provided by the video streaming cloud,  like Qiniu.

**Comment by DreamXiao** [comment]
@ltebean I didn't set up my own rtmp server, just run 'node app.js' and changed serverurl .
it was weird that for the first run it worked well...
If i want to run on localhost, what changes do i need?

**Comment by ltebean** [comment]
the rtmp server 139.196.232.10 is not live now, so when you push stream to that server, there will be an error

**Comment by DreamXiao** [comment]
@ltebean Is there a backup rtmp server addr？

**Comment by ltebean** [comment]
You need to set up your own, the tutorial is here: https://www.atlantic.net/community/howto/install-rtmp-ubuntu-14-04/.

**Comment by DreamXiao** [comment]
@ltebean ok.Thanks
