### ISSUE TITLE
Can't run on physical device

### ISSUE THREAD

**Issue by dmdque** [ltebean/Live#13]
I'm trying to run this project on a 1st gen iPad mini with iOS 9.3.3. The build fails with these errors:

![image](https://cloud.githubusercontent.com/assets/5205766/18970492/7f92f584-865f-11e6-9b41-f460033b488a.png)

I'm able to run it fine on the simulator though.

**Comment by San-Jeevan** [comment]
Go  to ijk library and download the latest version and compile it.
then replace the ijk library in ltebean project
