### ISSUE TITLE
Header 'TextAttributes-Swift.h' not found

### ISSUE THREAD

**Issue by dung07t2** [ltebean/Live#14]
I have an issue. pls tell me how to fix it?

**Comment by dung07t2** [comment]
@ltebean pls

**Comment by ImranIB** [comment]
![screen shot 2016-10-05 at 12 44 27 pm](https://cloud.githubusercontent.com/assets/10369328/19105101/ae524d72-8af9-11e6-8d44-767cbec3c434.png)

I also stuck on the same issue. Kindly help.

**Comment by ltebean** [comment]
Are you using Swift 3 or 2.3?

**Comment by ImranIB** [comment]
currently i m using swift 2.

**Comment by ltebean** [comment]
It's weird, maybe you can try `clean` and `delete derived data`, if it still doesn't work, you can remove this pod and comment out the code using it, there's very little code depending on it.

**Comment by dung07t2** [comment]
I found solution. After running pod install. You need restart xcode. I'm using xcode 7. It not working in xcode8

**Comment by ltebean** [comment]
I just updated the project to Swift 3
