### ISSUE TITLE
Archive clang error at IJKMediaFramework

### ISSUE THREAD

**Issue by yasuralian** [ltebean/Live#15]
```
ld: bitcode bundle could not be generated because '.../Live/live-ios/IJKMediaFramework.framework/IJKMediaFramework(IJKMediaPlayback.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I succeeded to run Live, but failed to archive it.
Do you have any suggestion that I should do?

**Comment by yasuralian** [comment]
I succeeded to archive Live demo by by getting `IJKMediaFramework` from original github.
I wish you would update `IJKMediaFramework`.
Thank you for reading!

**Comment by San-Jeevan** [comment]
already an issue on this #7

**Comment by BugKiller-tech** [comment]
@yasuralian  How did you build IJKMediaFramework from github?
How can I get the .framework ?
I built but I got .a file not .framework.
I have same issue for now. Please help me.

**Comment by speedoholic** [comment]
@RoraxHan You can download the framework source code from: https://github.com/Bilibili/ijkplayer
