### ISSUE TITLE
Bitcode bundle error while Archiving

### ISSUE THREAD

**Issue by ctufaro** [ltebean/Live#21]
The project builds just fine, however when I try to archive it, I receive the following:

ld: bitcode bundle could not be generated because '../pili-librtmp.framework/pili-librtmp(amf.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

I have a physical device connected (NOT a Simulator). I've set the enable_bitcode flags = NO at both the project and pod level. Nothing.

**Comment by ltebean** [comment]
You can rebuild the ijkplayer framework and replace the one in the project with the newly built one. Reference: https://github.com/Bilibili/ijkplayer

**Comment by BugKiller-tech** [comment]
@ctufaro did you solve this problem? then how did you that?
I'm not sure how I can rebuild ijkplayer framework, when I build that I got .a file not the .framework.
