### ISSUE TITLE
App seems to be crashing when I try to create a room (start broadcasting) on a test phone

### ISSUE THREAD

**Issue by maochenw** [ltebean/Live#27]
Everything seems to work on simulator, I am able to start a broadcast room and find the room and start chatting and sending gifts in the room. 
However, when I load it to a test phone (iphone7), as soon as I click on the + to start a broadcast room, the app crashes. 

It seems that this is not successful in BroadcasterViewController: 
        let videoConfiguration = LFLiveVideoConfiguration.defaultConfiguration(for: .medium3)
I get a error "Protocol not available" 
Am I missing a step somewhere? Thank you so much!

**Comment by maochenw** [comment]
Resolved. 
need to add the following to info.plist, else the app will crash starting iOS 10.2
Privacy - Camera Usage Description 
Privacy - Microphone Usage Description

**Comment by ltebean** [comment]
Fixed in #29
