### ISSUE TITLE
Not able to make an ipa file

### ISSUE THREAD

**Issue by ricky3214** [ltebean/Live#30]
Hi, It is running successfully in simulator and device when connected to system.

But I am unable to make ipa file at the time of build. It is showing me 4 error. Please check screenshot.

Please help me to resolve the issue.
<img width="1440" alt="screen shot 2017-06-28 at 4 33 32 pm" src="https://user-images.githubusercontent.com/6348483/27634181-f65f3650-5c1f-11e7-9ca7-05690cf22a7a.png">

**Comment by ricky3214** [comment]
@ltebean - can you please help

**Comment by Rilu-Ril** [comment]
I have the same problem :(

**Comment by ricky3214** [comment]
Hi Sanira, I resolved the issue... try to remove armv7 from build architecture. Because Live does not support it now.

**Comment by BugKiller-tech** [comment]
@ricky3214  I gave all the good reaction to your solution. Thank you so much!!

**Comment by ricky3214** [comment]
@RoraxHan  Your welcome :)

**Comment by BugKiller-tech** [comment]
@ricky3214  Hello, I made ipa once but now I met the same problem. even I removed the armv7 for now.
