### ISSUE TITLE
error when creating archive

### ISSUE THREAD

**Issue by Trushangpatel** [ltebean/Live#34]
Error face  when create archive 
xcode version : 8.3

1)
	

> “_OBJC_CLASS_$IJKFFOptions”,referenced from:
> 	  Objc-class-ref in streaming_play.o

2)	
	

> “_IJKMPMoviePlayerLoadStateDidChangeNotification”,referenced from:
> 	  _TFC8stratafy14streaming_play14viewAillAppearfSbR_ in streaming_play.o

3)
	

> “_OBJC_CLASS_$IJKFFMoviePlayerController”,referenced from:
> 	  Objc-class-ref in streaming_play.o
> 	  Symbol(s) not found for architecture armv7

**Comment by ltebean** [comment]
You can rebuild the ijkplayer framework and replace the one in the project with the newly built one. Reference: https://github.com/Bilibili/ijkplayer
