### ISSUE TITLE
IJK player needs update

### ISSUE THREAD

**Issue by San-Jeevan** [ltebean/Live#7]
Hi,

I had two issues when I used this:
1. A stream video to B. A restarts streams. B can only see video no sound. 
2. No ARMV6 (Iphone 5, 5s) support.

I solved both problems by getting the IJK player from original github and recompiling it.

**Comment by SirSamShaw** [comment]
@San-Jeevan could you take a peek at my issue and help me out running the demo plz?

**Comment by ltebean** [comment]
see https://github.com/ltebean/Live/issues/15
