### ISSUE TITLE
Missing videocore pods?

### ISSUE THREAD

**Issue by SirSamShaw** [ltebean/Live#8]
Please help.. I ran the pod install and everything installed perfectly all dependencies. Opened the project and went to run on my device and I am getting errors.. ran multiple pod installs with success, but not sure why I am missing these files. I went to videoCore directly and copied the mixers folder in.. still no dice.. 
<img width="249" alt="screen shot 2016-09-01 at 1 26 22 pm" src="https://cloud.githubusercontent.com/assets/17830626/18177387/fd477d16-7047-11e6-8f72-1e2bb51fb2e5.png">

**Comment by onlyEatMeat** [comment]
sorry,I'm Chinese,and my English is so poor.When you send me this mail, my local time is half past one in the evening.you can check the header     Build Setting ->Header Search Paths

**Comment by SirSamShaw** [comment]
ok I checked, but nothing is working. I can not run the sample.

**Comment by SirSamShaw** [comment]
@ltebean

**Comment by ltebean** [comment]
@SirSamShaw use cocoapods 0.39.0

**Comment by onlyEatMeat** [comment]
@ltebean  I use cocoapods 1.0.0         It's  working

**Comment by ltebean** [comment]
I just changed the push lib to LFLiveKit, so there won't be problems with VideoCore now
