### ISSUE TITLE
Latency issue

### ISSUE THREAD

**Issue by chamroeunbm** [ltebean/Live#9]
Hi,
Thanks for sharing the great code. I try it with DigitalOcean server and choose the Singapore Data Center as it's closest to me.

**There's a problem with delay in the live video(Latency).**

Do you have any suggestion on hosting or configuration to do to reduce it to the minimum?

Thanks

**Comment by ltebean** [comment]
for how many seconds?

**Comment by chamroeunbm** [comment]
around 1 second.

**Comment by ltebean** [comment]
1s delay is already very short
generally, the acceptable range for rtmp delay is 2-4s

**Comment by chamroeunbm** [comment]
I have seen Bigo Live. its delay is 10-500ms(My guess)--nearly real time. I  think it's even better than Facebook live.
Just wonder how they achieve it.

**Comment by San-Jeevan** [comment]
theoretically if you are in same country as the relaying server you can get around 300ms.
Remember the latency will be like this:
Capture video, encode, packetize and send to server: 60ms
Server to process: 10ms
Stream receiving device to decode: 40ms
+ Round trip time forth and back from server: same country ~40-100ms.

but too many factors here. your device has to have good enough CPU.

Also I dont know Bigo Live, but they may be using webrtc?
Device-2-device streaming without relaying server.

**Comment by chamroeunbm** [comment]
@San-Jeevan: Thank you so much for explaining in detail. Much appreciated!
